version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: buildit-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: buildit

  backend:
    build:
      context: ./backend
    container_name: buildit-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
    environment:
      - MONGODB_URI=mongodb://mongo:27017/buildit
    command: npm run start  # importante: coincide con tu script definido

volumes:
  mongo_data:
