import type { SectionKey, TemplateLanguage } from "../templates/types";

// Textos fijos de las webs generadas, comunes a todas las plantillas. Cada
// plantilla puede añadir los suyos en su definición (strings) y se leen igual,
// con t("clave"), en el idioma que elige la web.

export const COMMON_STRINGS: Record<TemplateLanguage, Record<string, string>> = {
  es: {
    skip: "Saltar al contenido",
    menu: "Menú",
    openMenu: "Abrir menú",
    mainNav: "Navegación principal",
    email: "Email",
    phone: "Teléfono",
    address: "Dirección",
    hours: "Horario",
    whatsapp: "WhatsApp",
    writeWhatsapp: "Escribir por WhatsApp",
    writeUs: "Escríbenos",
    callUs: "Llámanos",
    visitUs: "Visítanos",
    directions: "Cómo llegar",
    contact: "Contacto",
    learnMore: "Más información",
    seeMore: "Ver más",
    buy: "Comprar",
    book: "Reservar",
    choose: "Elegir",
    playVideo: "Reproducir vídeo",
    watchVideo: "Ver el vídeo",
    backToTop: "Volver arriba",
    rights: "Todos los derechos reservados.",
    madeWith: "Web creada con",
    question: "Pregunta",
  },
  en: {
    skip: "Skip to content",
    menu: "Menu",
    openMenu: "Open menu",
    mainNav: "Main navigation",
    email: "Email",
    phone: "Phone",
    address: "Address",
    hours: "Opening hours",
    whatsapp: "WhatsApp",
    writeWhatsapp: "Message us on WhatsApp",
    writeUs: "Write to us",
    callUs: "Call us",
    visitUs: "Visit us",
    directions: "Get directions",
    contact: "Contact",
    learnMore: "Learn more",
    seeMore: "See more",
    buy: "Buy",
    book: "Book",
    choose: "Choose",
    playVideo: "Play video",
    watchVideo: "Watch the video",
    backToTop: "Back to top",
    rights: "All rights reserved.",
    madeWith: "Made with",
    question: "Question",
  },
};

/** Nombre genérico de cada sección, para el menú cuando la plantilla no da otro. */
export const SECTION_NAMES: Record<TemplateLanguage, Record<Exclude<SectionKey, "brand">, string>> = {
  es: {
    hero: "Inicio",
    about: "Nosotros",
    features: "Servicios",
    products: "Productos",
    gallery: "Galería",
    video: "Vídeo",
    stats: "Cifras",
    steps: "Cómo trabajamos",
    team: "Equipo",
    testimonials: "Opiniones",
    documentation: "Documentos",
    faqs: "Preguntas",
    inspiration: "Inspiración",
    program: "Programa",
    cta: "Llamada a la acción",
    contact: "Contacto",
    footer: "Pie",
  },
  en: {
    hero: "Home",
    about: "About",
    features: "Services",
    products: "Products",
    gallery: "Gallery",
    video: "Video",
    stats: "Numbers",
    steps: "How it works",
    team: "Team",
    testimonials: "Reviews",
    documentation: "Documents",
    faqs: "FAQ",
    inspiration: "Inspiration",
    program: "Program",
    cta: "Call to action",
    contact: "Contact",
    footer: "Footer",
  },
};
